name = "infra"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
glinfra = { path = "../glinfra" }
glinfra_providers = { path = "../glinfra_providers" }
cymbal = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
