name = "glinfra"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
cymbal = { git = "https://github.com/nicolaschan/cymbal.git", ref = "main" }
simplifile = ">= 2.3.2 and < 3.0.0"
yay = ">= 2.0.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
