---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: Kustomization
resources:
- "minecraft.yaml"
- "ollama.yaml"
- "mines.yaml"
- "market.yaml"
- "x3dtictactoe.yaml"
- "baybridge.yaml"
- "traefik-middlewares.yaml"
- "cert-manager-issuers.yaml"
